HOST = '0.0.0.0'
PORT = 5000
DBHOST = 'localhost'
DBPORT = 3306
DBUSER = 'pegasus'
DBPASS = 'pegasus'
DBNAME = 'pegasus_metrics'
DEBUG = False
LOGLEVEL = 'INFO'
LOGFORMAT = "%(asctime)-15s %(levelname)s %(name)s (%(filename)s:%(lineno)s) %(message)s"
